server.port: 8082

spring:
  profiles:
  datasource:
    platform:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
    initialization-mode:
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
  h2:
    console:
    enabled: true
    path: /h2-console
